INSERT INTO Schools (code, name) VALUES
('RG', 'Registrar'),
('SB', 'School Behavioral/Social Sci'),
('ML', 'Modern Language'),
('PA', 'Physicians Assistant Studies'),
('PT', 'Dr. Physical Therapy'),
('BZ', 'MA School Psychology'),
('ART', 'Art'),
('HU', 'Humanities'),
('CC', 'School Computer Sci/ Math'),
('MG', 'Management Studies'),
('CA', 'Communiation the Arts'),
('BH', 'Mental Health Counseling'),
('CS', 'MSCS Computer Science'),
('MT', 'MS Technology Management'),
('SI', 'School of Science'),
('SM', 'School of Management'),
('SC', 'Science'),
('BT', 'MA in Teaching'),
('CMA', 'Comm Media Arts'),
('MP', 'MPA'),
('AAH', 'Art and Art History'),
('LA', 'School of Liberal Arts'),
('ENG', 'English'),
('CF', 'MS Global Fashion Merch'),
('BE', 'MS Education'),
('PP', 'Professional Programs'),
('MA', 'Professional Accountancy'),
('CW', 'Museum Studies'),
('BS', 'Behavioral/Social Science'),
('GP', 'Global and Profess Programs'),
('CO', 'School Communication  Arts'),
('AT', 'MS Athletic Training'),
('FA', 'Fashion'),
('BX', 'MA Psychology'),
('CX', 'MA Communication'),
('AL', 'Arts and Letters'),
('BY', 'MA Ed. Psychology'),
('MB', 'MBA')
;
INSERT INTO Subjects (code, name, schoolCode) VALUES
('PHTH', 'Physical Therapy', 'PT'),
('IENS', 'Environ Science-Internatal', 'SI'),
('IGEO', 'Geography-International', 'LA'),
('MBAM', 'MBA Module', 'MB'),
('GBST', 'Global Studies', 'LA'),
('SOC', 'Sociology', 'SB'),
('CSDR', 'Culture Studies Domican Rep', 'RG'),
('MUS', 'Music', 'CO'),
('OLC', 'Organizational Lead &amp;amp; Comm', 'GP'),
('ARCH', 'Architecture - LDM', 'CO'),
('KOR', 'Korean', 'LA'),
('ICOM', 'Communications-International', 'CA'),
('IPHL', 'Philosophy-International', 'LA'),
('AMST', 'American Studies', 'LA'),
('FDS', 'Fashion Design', 'CA'),
('MSPA', 'Professional Accountancy', 'MA'),
('ANTH', 'Anthropology', 'LA'),
('LANG', 'Language', 'LA'),
('IART', 'Art-International', 'CO'),
('IMUS', 'Music-International', 'CO'),
('ENG', 'English', 'LA'),
('CSJP', 'Culture Studies Japan', 'LA'),
('CSAU', 'Culture Studies Australia', 'LA'),
('LERN', 'Learning Center', 'LA'),
('CSHU', 'Culture Studies Hungary', 'RG'),
('FYS', 'First Year Seminar', 'LA'),
('FLOR', 'Florence Spring 2020', 'RG'),
('LERN', 'Learning Center', 'RG'),
('GERM', 'German', 'LA'),
('GRAP', 'Graphics - LDM', 'CO'),
('CSKO', 'Culture Studies-Korea', 'LA'),
('MSCM', 'Masters - MSCS Module', 'CS'),
('IORG', 'Organizational Admin-Internat', 'PP'),
('ADVT', 'Advertising', 'CO'),
('IFAS', 'Fashion-International', 'CA'),
('CSIS', 'Computer Science Info Sys', 'CC'),
('ESOL', 'English-ESOL', 'LA'),
('IENG', 'English-International', 'LA'),
('IMGT', 'Management Studies-Internation', 'PP'),
('CSIR', 'Culture Studies Ireland', 'LA'),
('ENGH', 'English-Honors', 'LA'),
('PA', 'Physician Assistant Studies', 'PA'),
('EPSY', 'Master Ed. Psychology', 'BY'),
('CHIN', 'Chinese', 'LA'),
('EDU', 'Education-LdM', 'SB'),
('CSSP', 'Culture Studies Spain', 'LA'),
('CHIN', 'Chinese', 'RG'),
('DATA', 'Data Science+Analytics', 'CC'),
('IHST', 'History-International', 'LA'),
('CAST', 'Catholic Studies', 'LA'),
('IPOS', 'Political Science-Internationa', 'LA'),
('IFRN', 'French-International', 'LA'),
('CSCA', 'Culture Studies-Catalan', 'LA'),
('CSSA', 'Culture Studies-Africa', 'LA'),
('CSCH', 'Culture Studies China', 'LA'),
('CSEU', 'European Project', 'LA'),
('MSTM', 'Masters - Technology Managment', 'MT'),
('PSYC', 'Psychology', 'SB'),
('EFL', 'English as Foreign Language', 'LA'),
('CSIT', 'Culture Studies Italy', 'SI'),
('ENG', 'English', 'CO'),
('GREK', 'Greek', 'LA'),
('ICSI', 'Cultural Studies-International', 'LA'),
('CSPO', 'Culture Studies-Poland', 'LA'),
('IMDA', 'Media Studies-International', 'CO'),
('WMST', 'Women&amp;#39;s Studies', 'LA'),
('HLTH', 'Health Education', 'SI'),
('IECO', 'Economics-International', 'MG'),
('ACCT', 'Accounting', 'SM'),
('IANT', 'Anthropology-International', 'SI'),
('CSMO', 'Culture Studies-Mongolian', 'LA'),
('SCI', 'Science', 'SI'),
('IECO', 'Economics-International', 'SM'),
('COM', 'Communication', 'CO'),
('CSIT', 'Culture Studies Italy', 'LA'),
('POSC', 'Political Science', 'LA'),
('CSRU', 'Culture Studies Russia', 'LA'),
('POLI', 'Political Science - LDM', 'LA'),
('CSBR', 'British Life &amp;amp; Culture', 'LA'),
('ADM', 'Admissions Intern', 'RG'),
('HONR', 'Honors', 'RG'),
('EMS', 'Emergency Med Tech', 'SI'),
('IPHL', 'Philosophy-International', 'HU'),
('ISPA', 'Spanish-International', 'BS'),
('MBA', 'Masters - MBA', 'MB'),
('ARTL', 'Art History - LDM', 'CO'),
('ICOM', 'Communications-International', 'CO'),
('MSCS', 'Master Computer Science', 'CS'),
('CHEM', 'Chemistry', 'SI'),
('MATH', 'Mathematics', 'CC'),
('MGMT', 'Management Studies', 'PP'),
('CSPG', 'Culture Studies-Portuguese', 'LA'),
('EDAC', 'Education-Advanced Certificate', 'BY'),
('ISOC', 'Sociology-International', 'SB'),
('CSAR', 'Culture Studies Arabic', 'LA'),
('MHEX', 'Mid Hudson Exchange', 'RG'),
('CSCU', 'Culture Studies', 'LA'),
('CSSE', 'Culture Studies-Serbia', 'LA'),
('IITA', 'Italian-International', 'LA'),
('MS', 'Military Science', 'SM'),
('ATHT', 'Athletic Training', 'AT'),
('BIOL', 'Biology', 'SI'),
('CLDM', 'Communications - LDM', 'CO'),
('PHRS', 'Philsphy/Relig Studies - LDM', 'LA'),
('CMPT', 'Computing Technology', 'CC'),
('CSIN', 'Culture Studies India', 'LA'),
('MAP', 'Marist Abroad', 'RG'),
('GAME', 'Games', 'CO'),
('ART', 'Art', 'AL'),
('ENSC', 'Environmental Science', 'SI'),
('MPA', 'Masters - MPA', 'MP'),
('COMI', 'Master IMC', 'CX'),
('PSYG', 'Masters - Psychology', 'BX'),
('MATA', 'Masters in Teaching Adol Edu', 'BT'),
('PHYS', 'Physics', 'SI'),
('REST', 'Religious Studies', 'LA'),
('LIT', 'Literature - LDM', 'LA'),
('ITAL', 'Italian', 'LA'),
('CSSM', 'Culture Studies-Samoa', 'LA'),
('LAT', 'Latin', 'LA'),
('ESL', 'English as a Second Language', 'LA'),
('FASH', 'Fashion', 'CO'),
('SOCW', 'Social Work', 'SB'),
('AFRK', 'Africa', 'LA'),
('DUBL', 'Dublin Course', 'RG'),
('IPOS', 'Political Science-Internationa', 'SB'),
('HIST', 'History', 'LA'),
('MSIS', 'Master Information Systems', 'CS'),
('IS', 'Information Systems', 'CC'),
('IMDA', 'Media Studies-International', 'CA'),
('IFAS', 'Fashion-International', 'CO'),
('GFSM', 'Global Fashion Merchandising', 'CF'),
('MEDT', 'Medical Technology', 'SI'),
('IART', 'Art-International', 'CA'),
('IBIO', 'Biology-International', 'SC'),
('INTD', 'Integrative Major', 'PP'),
('CSTH', 'Cultural Studies-Thai', 'LA'),
('FYSH', 'First Year Seminar-Honors', 'LA'),
('ELEC', 'General Elective', 'RG'),
('HST', 'History - LDM', 'LA'),
('REG', 'Miscellaneous', 'RG'),
('MDIA', 'Media Studies &amp;amp; Production', 'CO'),
('PSYH', 'Masters - School Psychology', 'BZ'),
('ARAB', 'Arabic', 'LA'),
('CSTZ', 'Cultural Studies-Tanzania', 'LA'),
('FCCU', 'Foreign Culture', 'LA'),
('ANTH', 'Anthropology', 'SI'),
('CMSC', 'Computer Science', 'CC'),
('IEDU', 'Education-International', 'SB'),
('CSAS', 'Culture Studies Asia', 'LA'),
('MGMT', 'Management Studies', 'PA'),
('ECON', 'Economics', 'MG'),
('COUN', 'MA CMH Counseling', 'BH'),
('POSC', 'Political Science', 'SB'),
('AGR', 'Agriculture-LdM', 'SI'),
('EDUC', 'Education', 'SB'),
('ITS', 'Information Tech &amp;amp; Sys', 'CC'),
('MSED', 'Master of Science in Education', 'BE'),
('ECON', 'Economics', 'SM'),
('BUS', 'Business', 'MG'),
('CSFR', 'Culture Studies France', 'LA'),
('JPN', 'Japanese', 'LA'),
('INTD', 'Integrative Major', 'GP'),
('BUS', 'Business', 'SM'),
('ART', 'Art', 'CO'),
('CSGR', 'Greek Civilization', 'LA'),
('CSBE', 'Culture Studies Belgium', 'LA'),
('RUSS', 'Russian', 'LA'),
('GEO', 'Geography', 'SI'),
('CONV', 'Conservator - LDM', 'CO'),
('ARTM', 'Museums and Public', 'CW'),
('ITDS', 'Interior Design - LDM', 'CO'),
('PRLG', 'Paralegal', 'LA'),
('SPAN', 'Spanish', 'LA'),
('FREN', 'French', 'LA'),
('ENSC', 'Environmental Science', 'SC'),
('ORG', 'Organizational Administration', 'PP'),
('PHIL', 'Philosophy', 'LA'),
('FLOR', 'Florence Spring 2020', 'LA'),
('CSGE', 'Culture Studies Germany', 'LA'),
('MEDU', 'Master of Educaton', 'BY'),
('STUD', 'Art Studio - LDM', 'CO'),
('IBUS', 'Business-International', 'SM'),
('COMG', 'Master Communication', 'CX'),
('IT', 'Information Technology', 'CC'),
('ISPA', 'Spanish-International', 'LA'),
('HONR', 'Honors', 'LA'),
('IJPN', 'Japanese-International', 'LA'),
('CRDV', 'Career Development', 'CO'),
('ATHT', 'Athletic Training', 'SI'),
('CSNL', 'Civilization of Netherlands', 'LA'),
('CRJU', 'Criminal Justice', 'SB'),
('PHED', 'Physical Education', 'SI'),
('CSSZ', 'Culture Studies-Czech', 'LA'),
('IRES', 'Religion-International', 'LA')
;
