INSERT INTO Schools (code, name) VALUES
('SM', 'School of Management'),
('RG', 'Registrar'),
('CO', 'School Communication  Arts'),
('LA', 'School of Liberal Arts'),
('SI', 'School of Science'),
('AL', 'Arts and Letters'),
('CA', 'Comm Media Arts'),
('CC', 'School Computer Sci/ Math'),
('SB', 'School Behavioral/Social Sci'),
('MG', 'Management Studies'),
('BY', 'MA Ed. Psychology'),
('AT', 'MS Athletic Training'),
('SC', 'Science'),
('PP', 'Professional Programs'),
('GP', 'Global and Profess Programs'),
('CF', 'MS Global Fashion Merch'),
('BH', 'Mental Health Counseling'),
('MB', 'MBA'),
('PA', 'Physicians Assistant Studies'),
('CX', 'MA Communication'),
('CS', 'MSCS Computer Science'),
('CW', 'Art and Art History'),
('HU', 'Humanities'),
('BE', 'MS Education'),
('MP', 'MPA'),
('BX', 'MA Psychology'),
('BZ', 'MA School Psychology'),
('MT', 'MS Technology Management'),
('BT', 'MA in Teaching'),
('PT', 'Dr. Physical Therapy'),
('MA', 'Professional Accountancy'),
('BS', 'Behavioral/Social Science')
;
INSERT INTO Subjects (code, name, schoolCode) VALUES
('ACCT', 'Accounting', 'SM'),
('ADM', 'Admissions Intern', 'RG'),
('ADVT', 'Advertising', 'CO'),
('AFRK', 'Africa', 'LA'),
('AGR', 'Agriculture-LdM', 'SI'),
('AMST', 'American Studies', 'LA'),
('ANTH', 'Anthropology', 'SI'),
('IANT', 'Anthropology-International', 'SI'),
('ARAB', 'Arabic', 'LA'),
('ARCH', 'Architecture - LDM', 'CO'),
('ART', 'Art', 'CO'),
('ARTL', 'Art History - LDM', 'CO'),
('STUD', 'Art Studio - LDM', 'CO'),
('IART', 'Art-International', 'CO'),
('CSNL', 'Civilization of Netherlands', 'LA'),
('COM', 'Communication', 'CO'),
('CLDM', 'Communications - LDM', 'CO'),
('ICOM', 'Communications-International', 'CA'),
('CMSC', 'Computer Science', 'CC'),
('CSIS', 'Computer Science Info Sys', 'CC'),
('CMPT', 'Computing Technology', 'CC'),
('CONV', 'Conservator - LDM', 'CO'),
('CRJU', 'Criminal Justice', 'SB'),
('ICSI', 'Cultural Studies-International', 'LA'),
('CSTZ', 'Cultural Studies-Tanzania', 'LA'),
('CSTH', 'Cultural Studies-Thai', 'LA'),
('CSCU', 'Culture Studies', 'LA'),
('CSAR', 'Culture Studies Arabic', 'LA'),
('CSAS', 'Culture Studies Asia', 'LA'),
('CSAU', 'Culture Studies Australia', 'LA'),
('CSBE', 'Culture Studies Belgium', 'LA'),
('CSCH', 'Culture Studies China', 'LA'),
('CSDR', 'Culture Studies Domican Rep', 'RG'),
('CSFR', 'Culture Studies France', 'LA'),
('CSGE', 'Culture Studies Germany', 'LA'),
('CSHU', 'Culture Studies Hungary', 'RG'),
('CSIN', 'Culture Studies India', 'LA'),
('CSIR', 'Culture Studies Ireland', 'LA'),
('CSIT', 'Culture Studies Italy', 'LA'),
('CSJP', 'Culture Studies Japan', 'LA'),
('CSRU', 'Culture Studies Russia', 'LA'),
('CSSP', 'Culture Studies Spain', 'LA'),
('CSSA', 'Culture Studies-Africa', 'LA'),
('CSCA', 'Culture Studies-Catalan', 'LA'),
('CSSZ', 'Culture Studies-Czech', 'LA'),
('CSKO', 'Culture Studies-Korea', 'LA'),
('CSMO', 'Culture Studies-Mongolian', 'LA'),
('CSPO', 'Culture Studies-Poland', 'LA'),
('CSPG', 'Culture Studies-Portuguese', 'LA'),
('CSSM', 'Culture Studies-Samoa', 'LA'),
('CSSE', 'Culture Studies-Serbia', 'LA'),
('DATA', 'Data Science+Analytics', 'CC'),
('DUBL', 'Dublin Course', 'RG'),
('ECON', 'Economics', 'SM'),
('IECO', 'Economics-International', 'SM'),
('EDUC', 'Education', 'SB'),
('EDAC', 'Education-Advanced Certificate', 'BY'),
('IEDU', 'Education-International', 'SB'),
('EDU', 'Education-LdM', 'SB'),
('EMS', 'Emergency Med Tech', 'SI'),
('ENG', 'English', 'LA'),
('ATHT', 'Athletic Training', 'SI'),
('BIOL', 'Biology', 'SI'),
('IBIO', 'Biology-International', 'SC'),
('CSBR', 'British Life &amp;amp; Culture', 'LA'),
('BUS', 'Business', 'SM'),
('IBUS', 'Business-International', 'SM'),
('CRDV', 'Career Development', 'CO'),
('CAST', 'Catholic Studies', 'LA'),
('CHEM', 'Chemistry', 'SI'),
('CHIN', 'Chinese', 'LA'),
('HIST', 'History', 'LA'),
('HST', 'History - LDM', 'LA'),
('IHST', 'History-International', 'LA'),
('HONR', 'Honors', 'RG'),
('IS', 'Information Systems', 'CC'),
('ITS', 'Information Tech &amp;amp; Sys', 'CC'),
('IT', 'Information Technology', 'CC'),
('INTD', 'Integrative Major', 'PP'),
('ITDS', 'Interior Design - LDM', 'CO'),
('ITAL', 'Italian', 'LA'),
('EFL', 'English as Foreign Language', 'LA'),
('ESL', 'English as a Second Language', 'LA'),
('ESOL', 'English-ESOL', 'LA'),
('ENGH', 'English-Honors', 'LA'),
('IENG', 'English-International', 'LA'),
('IENS', 'Environ Science-Internatal', 'SI'),
('ENSC', 'Environmental Science', 'SI'),
('CSEU', 'European Project', 'LA'),
('FASH', 'Fashion', 'CO'),
('FDS', 'Fashion Design', 'CA'),
('IFAS', 'Fashion-International', 'CO'),
('FYS', 'First Year Seminar', 'LA'),
('FYSH', 'First Year Seminar-Honors', 'LA'),
('FLOR', 'Florence Spring 2020', 'RG'),
('FCCU', 'Foreign Culture', 'LA'),
('FREN', 'French', 'LA'),
('IFRN', 'French-International', 'LA'),
('GAME', 'Games', 'CO'),
('ELEC', 'General Elective', 'RG'),
('GEO', 'Geography', 'SI'),
('IGEO', 'Geography-International', 'LA'),
('GERM', 'German', 'LA'),
('GFSM', 'Global Fashion Merchandising', 'CF'),
('GBST', 'Global Studies', 'LA'),
('GRAP', 'Graphics - LDM', 'CO'),
('GREK', 'Greek', 'LA'),
('CSGR', 'Greek Civilization', 'LA'),
('HLTH', 'Health Education', 'SI'),
('IITA', 'Italian-International', 'LA'),
('JPN', 'Japanese', 'LA'),
('IJPN', 'Japanese-International', 'LA'),
('KOR', 'Korean', 'LA'),
('LANG', 'Language', 'LA'),
('LAT', 'Latin', 'LA'),
('LERN', 'Learning Center', 'LA'),
('LIT', 'Literature - LDM', 'LA'),
('COUN', 'MA CMH Counseling', 'BH'),
('MBAM', 'MBA Module', 'MB'),
('MGMT', 'Management Studies', 'PP'),
('IMGT', 'Management Studies-Internation', 'PP'),
('MAP', 'Marist Abroad', 'RG'),
('COMG', 'Master Communication', 'CX'),
('MSCS', 'Master Computer Science', 'CS'),
('EPSY', 'Master Ed. Psychology', 'BY'),
('MDIA', 'Media Studies &amp;amp; Production', 'CO'),
('IMDA', 'Media Studies-International', 'CO'),
('MEDT', 'Medical Technology', 'SI'),
('MHEX', 'Mid Hudson Exchange', 'RG'),
('MS', 'Military Science', 'SM'),
('REG', 'Miscellaneous', 'RG'),
('ARTM', 'Museums and Public', 'CW'),
('MUS', 'Music', 'CO'),
('IMUS', 'Music-International', 'CO'),
('IORG', 'Organizational Admin-Internat', 'PP'),
('ORG', 'Organizational Administration', 'PP'),
('OLC', 'Organizational Lead &amp;amp; Comm', 'GP'),
('PRLG', 'Paralegal', 'LA'),
('PHIL', 'Philosophy', 'LA'),
('IPHL', 'Philosophy-International', 'HU'),
('PHRS', 'Philsphy/Relig Studies - LDM', 'LA'),
('ISPA', 'Spanish-International', 'LA'),
('WMST', 'Women&amp;#39;s Studies', 'LA'),
('COMI', 'Master IMC', 'CX'),
('MSIS', 'Master Information Systems', 'CS'),
('MEDU', 'Master of Educaton', 'BY'),
('MSED', 'Master of Science in Education', 'BE'),
('MBA', 'Masters - MBA', 'MB'),
('MPA', 'Masters - MPA', 'MP'),
('MSCM', 'Masters - MSCS Module', 'CS'),
('PSYG', 'Masters - Psychology', 'BX'),
('PSYH', 'Masters - School Psychology', 'BZ'),
('MSTM', 'Masters - Technology Managment', 'MT'),
('MATA', 'Masters in Teaching Adol Edu', 'BT'),
('MATH', 'Mathematics', 'CC'),
('PHED', 'Physical Education', 'SI'),
('PHTH', 'Physical Therapy', 'PT'),
('PA', 'Physician Assistant Studies', 'PA'),
('PHYS', 'Physics', 'SI'),
('POSC', 'Political Science', 'LA'),
('POLI', 'Political Science - LDM', 'LA'),
('IPOS', 'Political Science-Internationa', 'LA'),
('MSPA', 'Professional Accountancy', 'MA'),
('PSYC', 'Psychology', 'SB'),
('IRES', 'Religion-International', 'LA'),
('REST', 'Religious Studies', 'LA'),
('RUSS', 'Russian', 'LA'),
('SCI', 'Science', 'SI'),
('SOCW', 'Social Work', 'SB'),
('SOC', 'Sociology', 'SB'),
('ISOC', 'Sociology-International', 'SB'),
('SPAN', 'Spanish', 'LA')
;
